apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "garage.fullname" . }}
  labels:
    {{- include "garage.labels" . | nindent 4 }}
data:
  garage.toml: |
    metadata_dir = "/var/lib/garage/meta"
    data_dir = "/var/lib/garage/data"
    db_engine = "lmdb"

    replication_mode = "none"

    rpc_bind_addr = "[::]:3901"
    rpc_secret_file = "/etc/garage/secrets/rpc-secret"

    [s3_api]
    s3_region = "garage"
    api_bind_addr = "[::]:3900"
    root_domain = ".s3.garage.localhost"

    [s3_web]
    bind_addr = "[::]:3902"
    root_domain = ".web.garage.localhost"

    [admin]
    api_bind_addr = "0.0.0.0:3903"
    admin_token_file = "/etc/garage/secrets/admin-token"
