{{- $existing := lookup "v1" "Secret" .Release.Namespace (printf "%s-garage" .Release.Name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "garage.fullname" . }}
  labels:
    {{- include "garage.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if $existing }}
  admin-token: {{ index $existing.data "admin-token" }}
  rpc-secret: {{ index $existing.data "rpc-secret" }}
  {{- else }}
  admin-token: {{ .Values.adminToken | default (randAlphaNum 32) | b64enc | quote }}
  rpc-secret: {{ genPrivateKey "ed25519" | sha256sum | b64enc | quote }}
  {{- end }}
