apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
data:
  {{- /* Additional non-sensitive env vars to be sourced from a ConfigMap */}}
  {{- if .Values.mlflow.env.configMap}}
  {{- with .Values.mlflow.env.configMap }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
