{{- if .Values.postgres.enabled }}
apiVersion: v1
stringData:
  username: {{ .Values.postgres.auth.username }}
  password: {{ .Values.postgres.auth.password }}
kind: Secret
metadata:
  name: mlflow-postgres-init
type: kubernetes.io/basic-auth
---
{{- end }}
{{- if .Values.mlflow.trackingServer.basicAuth.enabled }}
{{- if not .Values.mlflow.trackingServer.basicAuth.existingSecret }}
apiVersion: v1
stringData:
  {{- if $.Values.postgres.external.enabled }}
  POSTGRES_USER: {{ .Values.postgres.auth.username }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password }}
  POSTGRES_HOST: {{ .Values.postgres.external.host }}
  POSTGRES_PORT: {{ .Values.postgres.external.port }}
  POSTGRES_DB: {{ .Values.postgres.external.database }}
  {{- else }}
  POSTGRES_USER: {{ .Values.postgres.auth.username }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password }}
  POSTGRES_HOST: "postgres-rw"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: {{ .Values.postgres.cluster.initdb.database }}
  {{- end }}
kind: Secret
metadata:
  name: mlflow-waitfor-postgres
type: Opaque
{{- end }}
{{- end }}
