apiVersion: v1
kind: Service
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
  {{- with .Values.mlflow.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.mlflow.service.type }}
  ports:
  - port: {{ .Values.mlflow.service.port }}
    targetPort: http
    protocol: TCP
    name: {{ .Values.mlflow.service.name }}
    nodePort: {{ .Values.mlflow.service.nodePort }}
  selector:
    {{- include "mlflow.selectorLabels" . | nindent 4 }}
