{{- if .Values.minio.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.minio.secrets.name }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER={{ .Values.minio.secrets.accessKey | quote }}
    export MINIO_ROOT_PASSWORD={{ .Values.minio.secrets.secretKey | quote }}
{{- end }}
