apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.fullname" . }}
  labels:
    {{- include "mlflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- $dbUri := (printf "postgresql://%s:%s@%s:%s/%s" .Values.postgres.auth.username .Values.postgres.auth.password (printf "%s-postgres-rw" (include "mlflow.fullname" .)) "5432" .Values.postgres.embedded.initdb.database) }}
  {{- if .Values.postgres.external.enabled }}
  {{- $dbUri = (printf "postgresql://%s:%s@%s:%s/%s" .Values.postgres.auth.username .Values.postgres.auth.password .Values.postgres.external.host .Values.postgres.external.port .Values.postgres.external.database) }}
  {{- end }}

  {{- /* Backend Store */}}
  {{- $modes := list "serve-artifacts" "no-serve-artifacts" }}
  {{- if has .Values.mlflow.trackingServer.mode $modes }}
  {{- if not .Values.mlflow.backendStore.existingSecret }}
  MLFLOW_BACKEND_STORE_URI: {{ $dbUri }}
  {{- end }}
  {{- end }}

  {{- /* Use AWS S3 as aftifact store */}}
  {{- if .Values.mlflow.artifactStore.s3.enabled }}
  {{- if not .Values.mlflow.artifactStore.s3.existingSecret }}
  {{- if .Values.minio.enabled }}
  MLFLOW_S3_ENDPOINT_URL: {{ printf "https://%s:%s" .Values.minio.tenant.name "443" }}
  MLFLOW_S3_IGNORE_TLS: {{ .Values.mlflow.artifactStore.s3.ignoreTls | quote }}
  {{- else if .Values.mlflow.artifactStore.s3.external.enabled }}
  MLFLOW_S3_ENDPOINT_URL: {{ printf "%s://%s:%s" .Values.mlflow.artifactStore.s3.external.protocol .Values.mlflow.artifactStore.s3.external.host .Values.mlflow.artifactStore.s3.external.port }}
  MLFLOW_S3_IGNORE_TLS: {{ .Values.mlflow.artifactStore.s3.external.ignoreTls | quote }}
  {{- end }}
  {{- with .Values.mlflow.artifactStore.s3.accessKeyId }}
  AWS_ACCESS_KEY_ID: {{ . }}
  {{- end }}
  {{- with .Values.mlflow.artifactStore.s3.secretAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ . }}
  {{- end }}
  {{- end }}
  {{- if not .Values.mlflow.artifactStore.s3.existingCaSecret }}
  {{- with .Values.mlflow.artifactStore.s3.createCaSecret.caBundle }}
  AWS_CA_BUNDLE: {{ . }}
  {{- end }}
  {{- end }}
  {{- end }}

  {{- /* Additional env vars to be sourced from a Secret */}}
  {{- if .Values.mlflow.env.secret }}
  {{- with .Values.mlflow.env.secret }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
