apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: traefik
spec:
  chart:
    name: traefik
    chartVersion: '1.0.0'
  weight: 2
  helmUpgradeFlags:
    - --wait
  namespace: traefik
  builder: {}
