name: Airgap Build and Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the chart to test'
        required: true
        default: '0.2.0'

env:
  chart_name: replibot
  app_id: 2S2KBYYp3fKkP42pb3eJYIYJNYv
        

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_SLUG: "dexter-test3"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Channel Release Sequence
        id: get-channel-release-sequence
        run: |
          curl --request GET \
            --url https://api.replicated.com/vendor/v3/app/${{ env.app_id }}/channel/2pusnQ3dbpDq0SEVEE8LCeUCCwC/releases \
            --header 'Authorization: ${{ secrets.REPLICATED_API_TOKEN }}' \
            --header 'accept: application/json' | jq -r '.releases[0].channelSequence' > channel-release-sequence.txt
          echo "channel-release-sequence=$(cat channel-release-sequence.txt)" >> $GITHUB_OUTPUT
    
      - name: build airgap
        run: |
          curl --request POST \
            --url https://api.replicated.com/vendor/v3/app/${{ env.app_id }}/channel/2pusnQ3dbpDq0SEVEE8LCeUCCwC/release/${{ steps.get-channel-release-sequence.outputs.channel-release-sequence }}/airgap/build \
            --header 'Authorization: ${{ secrets.REPLICATED_API_TOKEN }}' \
            --header 'accept: application/json'

      - name: Sleep for 60 seconds
        run: sleep 60s
        shell: bash
      
      - name: check airgap build success
        run: |
          max_retries=10
          attempt=0

          while true; do
            status=$(curl --silent --request GET \
              --url https://api.replicated.com/vendor/v3/app/${{ env.app_id }}/channel/2pusnQ3dbpDq0SEVEE8LCeUCCwC/releases \
              --header "Authorization: ${{ secrets.REPLICATED_API_TOKEN }}" \
              --header "accept: application/json" | jq -r '.releases[0].airgapBuildStatus')

            echo "Current airgapBuildStatus: $status"

            if [ "$status" == "built" ]; then
              echo "Airgap build is complete!"
              break
            elif [ "$status" == "failed" ]; then
              echo "Airgap build has failed. Exiting with error."
              exit 1
            elif [ "$status" == "building" ]; then
              echo "Airgap build is still in progress. Waiting for 60 seconds..."
              sleep 60
            fi

            attempt=$((attempt + 1))
            if [ "$attempt" -ge "$max_retries" ]; then
              echo "Maximum retries reached. Exiting with error."
              exit 1
            fi
          done
