apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: akkoma
spec:
  chart:
    name: akkoma
    chartVersion: 0.3.0
  values:
    akkoma:
      domain: repl{{ ConfigOption "akkoma_domain" }}
      adminEmail: repl{{ ConfigOption "akkoma_admin_email" }}
      instanceName: repl{{ ConfigOption "akkoma_instance_name" }}

    image:
      repository: repl{{ HasLocalRegistry | ternary LocalRegistryHost "ghcr.io" }}/adamancini/akkoma

    ingress:
      enabled: repl{{ ConfigOptionEquals "ingress_enabled" "1" }}
      className: repl{{ ConfigOption "ingress_class_name" }}
      tls:
        enabled: repl{{ ConfigOptionNotEquals "ingress_tls_type" "tls_none" }}
        secretName: repl{{ ConfigOption "ingress_tls_secret_name" }}

    postgresql:
      database: repl{{ ConfigOption "postgres_database" }}
      username: repl{{ ConfigOption "postgres_username" }}
      storageSize: repl{{ ConfigOption "postgres_storage_size" }}
      storageClass: repl{{ ConfigOption "postgres_storage_class" }}
      external:
        enabled: repl{{ ConfigOptionEquals "postgres_type" "postgres_external" }}
        host: repl{{ ConfigOption "postgres_external_host" }}
        port: repl{{ ConfigOption "postgres_external_port" }}
        database: repl{{ ConfigOption "postgres_database" }}
        username: repl{{ ConfigOption "postgres_username" }}
        passwordSecret: repl{{ ConfigOption "postgres_external_password_secret" }}
        passwordKey: repl{{ ConfigOption "postgres_external_password_key" }}

    storage:
      type: repl{{ ConfigOptionEquals "storage_type" "storage_local" | ternary "local" "s3" }}
      uploads:
        size: repl{{ ConfigOption "storage_uploads_size" }}
        storageClass: repl{{ ConfigOption "storage_uploads_class" }}
      s3:
        endpoint: repl{{ ConfigOption "s3_endpoint" }}
        region: repl{{ ConfigOption "s3_region" }}
        bucket: repl{{ ConfigOption "s3_bucket" }}
        baseUrl: repl{{ ConfigOption "s3_base_url" }}
        accessKeyId: repl{{ ConfigOption "s3_access_key" }}
        secretAccessKey: repl{{ ConfigOption "s3_secret_key" }}

    instance:
      characterLimit: repl{{ ConfigOption "akkoma_character_limit" }}
      registrationsOpen: repl{{ ConfigOptionEquals "akkoma_registrations_open" "1" }}
      uploadLimit: repl{{ ConfigOption "akkoma_upload_limit" }}
      description: repl{{ ConfigOption "akkoma_description" }}

    garage:
      enabled: repl{{ ConfigOptionEquals "garage_enabled" "1" }}
      persistence:
        meta:
          size: repl{{ ConfigOption "garage_meta_size" }}
        data:
          size: repl{{ ConfigOption "garage_data_size" }}

    metrics:
      enabled: repl{{ ConfigOptionEquals "metrics_enabled" "1" }}
      serviceMonitor:
        enabled: repl{{ ConfigOptionEquals "metrics_service_monitor_enabled" "1" }}

    networkPolicy:
      enabled: repl{{ ConfigOptionEquals "network_policy_enabled" "1" }}

  optionalValues:
    - when: 'repl{{ ConfigOptionEquals "ingress_tls_type" "tls_cert_manager" }}'
      recursiveMerge: true
      values:
        ingress:
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
