# MLFlow with external artifact store (AWS S3) using direct credentials

# Disable embedded MinIO since we'll use external S3
minio:
  enabled: false

# Configure MLflow to use external S3 as artifact store
mlflow:
  trackingServer:
    mode: serve-artifacts
    artifactsDestination: "s3://your-s3-bucket/mlflow"
    
  artifactStore:
    s3:
      enabled: true
      # Specify credentials directly (not recommended for production)
      accessKeyId: "your-aws-access-key-id"
      secretAccessKey: "your-aws-secret-access-key"
      ignoreTls: false
      external:
        enabled: true
        protocol: https
        host: "s3.amazonaws.com"
        port: 443
        ignoreTls: false
