apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-supportbundle
  labels:
    troubleshoot.sh/kind: support-bundle
type: Opaque
stringData:
  support-bundle-spec: |
{{ include "cert-manager.supportbundle" . | indent 4 }} 
