apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-preflights
  labels:
    troubleshoot.sh/kind: preflight
type: Opaque
stringData:
  preflight.yaml: |
    apiVersion: troubleshoot.sh/v1beta2
    kind: Preflight
    metadata:
      name: cert-manager-preflights
    spec:
      analyzers:
        # https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/README.template.md#prerequisites
        - clusterVersion:
            outcomes:
              - fail:
                  when: "< 1.22.0"
                  message: The application requires at least Kubernetes 1.22.0, and recommends 1.25.0.
                  uri: https://kubernetes.io
              - warn:
                  when: "< 1.25.0"
                  message: Your cluster meets the minimum version of Kubernetes, but we recommend you update to 1.25.0 or later.
                  uri: https://kubernetes.io
              - pass:
                  message: Your cluster meets the recommended and required versions of Kubernetes.