apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-preflights
  labels:
    troubleshoot.sh/kind: preflight
type: Opaque
stringData:
  preflight.yaml: |
{{ include "cert-manager.preflight" . | indent 4 }}