apiVersion: cluster.kurl.sh/v1beta1
kind: Installer
metadata:
  name: vaultwarden
spec:
  kubernetes:
    version: 1.29.x
  containerd:
    version: 1.7.x
  flannel:
    version: 0.25.x
  openebs:
    version: 3.10.x
    isLocalPVEnabled: true
    localPVStorageClassName: local
  minio:
    version: 2024-09-22T00-33-43Z
  kotsadm:
    version: latest
  registry:
    version: 2.8.x
  contour:
    version: 1.30.x
