# Default environment
default_env := "dev"

# Apply Helmfile with the specified environment
apply env=default_env:
    helmfile --environment {{env}} apply

# Template Helmfile with the specified environment
template env=default_env:
    helmfile --environment {{env}} template

# Sync Helmfile with the specified environment
sync env=default_env:
    helmfile --environment {{env}} sync

# Preview Helmfile diff with the specified environment
diff env=default_env:
    helmfile --environment {{env}} diff

# Deploy dev setup
dev:
    just apply dev

# Deploy prod setup (Postgres + Traefik Ingress)
prod:
    just apply prod

# Destroy all releases
destroy:
    helmfile --selector app=n8n-stack destroy --skip-charts
