# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/app-template-3.7.3/charts/other/app-template/values.schema.json
controllers:
  main:
    containers:
      main:
        securityContext:
          allowPrivilegeEscalation: false
          sysctls:
            - name: net.ipv4.ip_forward
              value: "1"
          capabilities:
            add:
              - NET_ADMIN
        image:
          repository: ghcr.io/wg-easy/wg-easy
          tag: 9.0
          pullPolicy: IfNotPresent
        ports:
          - containerPort: 51821
            protocol: TCP
          - containerPort: 51820
            protocol: UDP
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi

service:
  web:
    controller: main
    enabled: true
    type: ClusterIP
    ipFamilyPolicy: SingleStack
    ipFamilies:
      - IPv4
    ports:
      http:
        enabled: true
        port: 51821
        protocol: HTTP
  vpn:
    controller: main
    enabled: true
    type: LoadBalancer
    ipFamilyPolicy: SingleStack
    ipFamilies:
      - IPv4
    ports:
      udp:
        enabled: true
        port: 51820
        protocol: UDP

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ''
    accessMode: ReadWriteOnce
    size: 1Gi
    retain: false
    globalMounts:
      - path: /etc/wireguard

# Wireguard configuration
wireguard:
  # If password is defined will set a password on the web interface
  #password: supersecure
  # See https://github.com/WeeJeWel/wg-easy for configuration options
  host: vpn.example.com
  #port:
  #mtu:
  #persistentKeepalive:
  #defaultAddress:
  #defaultDns:
  #allowedIps:
  #preUp:
  #postUp:
  #preDown:
  #postDown:

# Troubleshoot
troubleshoot:
  support-bundles:
    # Replicated supplied default support bundle spec
    replicated:
      # -- Enables or disables the Replicated default support bundle
      enabled: true
