image:
  registry: docker.io
  repository: nicholasjackson/fake-service
  tag: v0.26.2
  pullPolicy: IfNotPresent
  imagePullSecrets: []

frontend:
  name: "frontend"
  message: "New frontend update! This is the way!"
  serverType: "http"
  logLevel: "debug"
  port: 9090

backend:
  name: "backend"
  message: "New backend update"
  serverType: "http"
  logLevel: "debug"
  port: 9091
  errorRate: 0
  origin: "*"

ingress-nginx:
  enabled: true
  imagePullSecrets: []
  controller:
    image:
      registry: registry.k8s.io
      image: ingress-nginx/controller
      tag: v1.11.3
      digest: ""
    admissionWebhooks:
      patch:
        image:
          registry: registry.k8s.io
          image: ingress-nginx/kube-webhook-certgen
          tag: v1.4.4
          digest: ""
    service:
      type: NodePort
      nodePorts:
        http: 80
        https: 443
  ingressClassResource:
    default: true

rqliteui:
  image:
    registry: docker.io
    repository: gerardnguyen/rqman
    tag: 0.0.3
    pullPolicy: IfNotPresent
    imagePullSecrets: []

cert-manager:
  enabled: true

ingress:
  host: gerard-vm.testcluster.net