version: "3"

# This is a shim taskfile for running tasks inside Podman
# The actual taskfile that is mounted within the container lives in taskfiles/internal.yaml

includes:
  container:
    internal: true
    taskfile: ./taskfiles/container.yml

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  helm:
    desc: 'Run helm with args inside the container (example: "task helm -- show chart ./cert-manager")'
    cmds:
      - task: container:exec
        vars:
          CMD: 'helm {{.CLI_ARGS}}'

  kubectl:
    desc: 'Run kubectl with args inside the container (example: "task kubectl -- version --client")'
    cmds:
      - task: container:exec
        vars:
          CMD: 'kubectl {{.CLI_ARGS}}'

  cluster-create:
    desc: Create a test cluster using Replicated Compatibility Matrix (use EMBEDDED=true for embedded clusters)
    cmds:
      - task: container:exec
        vars:
          CMD: 'task {{.TASK}}'

  list-cluster:
    desc: List the cluster
    cmds:
      - task: container:exec
        vars:
          CMD: 'task {{.TASK}}'

  test:
    desc: Run a basic test suite
    cmds:
      - task: container:exec
        vars:
          CMD: 'task {{.TASK}}'

  verify-kubeconfig:
    desc: Verify kubeconfig
    cmds:
      - task: container:exec
        vars:
          CMD: 'task {{.TASK}}'

  setup-kubeconfig:
    desc: Get kubeconfig and prepare cluster for application deployment
    cmds:
      - task: container:exec
        vars:
          CMD: 'task {{.TASK}}'

  dependencies-update:
    desc: Update Helm dependencies for all charts
    cmds:
      - task: container:exec
        vars:
          CMD: 'task {{.TASK}}'

  ports-expose:
    desc: Expose configured ports and capture exposed URLs
    cmds:
      - task: container:exec
        vars:
          CMD: 'task {{.TASK}}'

  helm-deploy:
    desc: Deploy all charts using helmfile
    cmds:
      - task: container:exec
        vars:
          CMD: 'task {{.TASK}}'

  cluster-delete:
    desc: Delete all test clusters with matching name and clean up kubeconfig
    cmds:
      - task: container:exec
        vars:
          CMD: 'task {{.TASK}}'

  release-prepare:
    desc: Prepare release files by copying replicated YAML files and packaging Helm charts
    cmds:
      - task: container:exec
        vars:
          CMD: 'task {{.TASK}}'

  release-create:
    desc: Create and promote a release using the Replicated CLI
    cmds:
      - task: container:exec
        vars:
          CMD: 'task {{.TASK}}'

  gcp-vm-create:
    desc: Create a simple GCP VM instance
    cmds:
      - task: container:exec
        vars:
          CMD: 'task {{.TASK}}'

  gcp-vm-delete:
    desc: Delete the GCP VM instance for K8s and VPN
    cmds:
      - task: container:exec
        vars:
          CMD: 'task {{.TASK}}'

  embedded-cluster-setup:
    desc: Setup Replicated embedded cluster on the GCP VM
    cmds:
      - task: container:exec
        vars:
          CMD: 'task {{.TASK}}'

  full-test-cycle:
    desc: Create cluster, get kubeconfig, expose ports, update dependencies, deploy charts, test, and delete
    cmds:
      - task: container:exec
        vars:
          CMD: 'task {{.TASK}}'
