version: "3"

# This is a shim taskfile for running tasks inside Podman
# The actual taskfile that is mounted within the container lives in taskfiles/internal.yaml

includes:
  dev: ./taskfiles/container.yml

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  cluster-create:
    desc: Create a test cluster using Replicated Compatibility Matrix (use EMBEDDED=true for embedded clusters)
    cmds:
      - task: dev:shell
        vars:
          CMD: "task cluster-create"

  list-cluster:
    desc: List the cluster
    cmds:
      - task: dev:shell
        vars:
          CMD: "task list-cluster"

  test:
    desc: Run a basic test suite
    cmds:
      - task: dev:shell
        vars:
          CMD: "task test"

  verify-kubeconfig:
    desc: Verify kubeconfig
    cmds:
      - task: dev:shell
        vars:
          CMD: "task verify-kubeconfig"

  setup-kubeconfig:
    desc: Get kubeconfig and prepare cluster for application deployment
    cmds:
      - task: dev:shell
        vars:
          CMD: "task setup-kubeconfig"

  dependencies-update:
    desc: Update Helm dependencies for all charts
    cmds:
      - task: dev:shell
        vars:
          CMD: "task dependencies-update"

  ports-expose:
    desc: Expose configured ports and capture exposed URLs
    cmds:
      - task: dev:shell
        vars:
          CMD: "task ports-expose"

  helm-deploy:
    desc: Deploy all charts using helmfile
    cmds:
      - task: dev:shell
        vars:
          CMD: "task helm-deploy"

  cluster-delete:
    desc: Delete all test clusters with matching name and clean up kubeconfig
    cmds:
      - task: dev:shell
        vars:
          CMD: "task cluster-delete"

  release-prepare:
    desc: Prepare release files by copying replicated YAML files and packaging Helm charts
    cmds:
      - task: dev:shell
        vars:
          CMD: "task release-prepare"

  release-create:
    desc: Create and promote a release using the Replicated CLI
    cmds:
      - task: dev:shell
        vars:
          CMD: "task release-create"

  gcp-vm-create:
    desc: Create a simple GCP VM instance
    cmds:
      - task: dev:shell
        vars:
          CMD: "task gcp-vm-create"

  gcp-vm-delete:
    desc: Delete the GCP VM instance for K8s and VPN
    cmds:
      - task: dev:shell
        vars:
          CMD: "task gcp-vm-delete"

  embedded-cluster-setup:
    desc: Setup Replicated embedded cluster on the GCP VM
    cmds:
      - task: dev:shell
        vars:
          CMD: "task embedded-cluster-setup"

  full-test-cycle:
    desc: Create cluster, get kubeconfig, expose ports, update dependencies, deploy charts, test, and delete
    cmds:
      - task: dev:shell
        vars:
          CMD: "task full-test-cycle"
