apiVersion: embeddedcluster.replicated.com/v1beta1
kind: Config
spec:
  version: 2.0.0+k8s-1.30
  extensions:
    helm:
      repositories:
        - name: cnpg
          url: https://cloudnative-pg.github.io/charts
        - name: minio-operator
          url: https://operator.min.io
        - name: jetstack
          url: https://charts.jetstack.io
        - name: ingress-nginx
          url: https://kubernetes.github.io/ingress-nginx
      charts:
        - name: cloudnative-pg
          chartname: cnpg/cloudnative-pg
          namespace: cnpg
          version: "0.22.1"
          values: |
            cloudnative-pg:
              enabled: true
        - name: minio-operator
          chartname: minio-operator/operator
          namespace: minio
          version: "6.0.4"
        - name: cert-manager
          chartname: jetstack/cert-manager
          namespace: cert-manager
          version: "v1.16.3"
          values: |
            crds:
              enabled: true
            prometheus:
              enabled: false
        - name: ingress-nginx
          chartname: ingress-nginx/ingress-nginx
          namespace: ingress-nginx
          version: "4.9.1"
          values: |
            controller:
              service:
                type: NodePort
                nodePorts:
                  http: 80
                  https: 443
