apiVersion: embeddedcluster.replicated.com/v1beta1
kind: Config
spec:
  version: 2.13.4+k8s-1.33
  domains:
    replicatedAppDomain: app.xyyzx.net
    proxyRegistryDomain: proxy.xyyzx.net
  extensions:
    helm:
      repositories:
        - name: cnpg
          url: https://cloudnative-pg.github.io/charts
        - name: minio-operator
          url: https://operator.min.io
        - name: jetstack
          url: https://charts.jetstack.io
        - name: ingress-nginx
          url: https://kubernetes.github.io/ingress-nginx
        - name: k8ssandra
          url: https://helm.k8ssandra.io/stable
      # NOTE: cert-manager MUST be first - k8ssandra cass-operator
      # webhooks require cert-manager CRDs to exist at install time.
      charts:
        - name: cert-manager
          chartname: jetstack/cert-manager
          namespace: cert-manager
          version: "v1.19.1"
          values: |
            crds:
              enabled: true
            prometheus:
              enabled: false
        - name: cloudnative-pg
          chartname: cnpg/cloudnative-pg
          namespace: cnpg
          version: "0.27.0"
          values: |
            cloudnative-pg:
              enabled: true
        - name: minio-operator
          chartname: minio-operator/operator
          namespace: minio
          version: "7.1.1"
        - name: ingress-nginx
          chartname: ingress-nginx/ingress-nginx
          namespace: ingress-nginx
          version: "4.14.1"
          values: |
            controller:
              service:
                type: NodePort
                nodePorts:
                  http: 80
                  https: 443
        - name: k8ssandra-operator
          chartname: k8ssandra/k8ssandra-operator
          namespace: k8ssandra-operator
          version: "1.22.0"
          values: |
            global:
              clusterScoped: true
