apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: storagebox
spec:
  title: StorageBox
  allowRollback: false
  statusInformers:
    - statefulset/kotsadm-rqlite
    - deployment/kotsadm
    - '{{repl if ConfigOptionEquals "cassandra_enabled" "1"}}cassandradatacenter/dc1{{repl end}}'
    - '{{repl if ConfigOptionEquals "rqlite_enabled" "1"}}statefulset/storagebox-rqlite{{repl end}}'
