apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: storagebox
spec:
  title: StorageBox
  allowRollback: false
  statusInformers:
    - deployment/kotsadm
    - statefulset/kotsadm-rqlite
    - statefulset/storagebox-cassandra
