apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: storagebox
spec:
  chart:
    name: storagebox
    chartVersion: 0.24.0
  values:
    global:
      imagePullSecrets:
        - name: repl{{ ImagePullSecretName }}
    images:
      busybox:
        repository: repl{{ HasLocalRegistry | ternary (print LocalRegistryHost "/library/busybox") "proxy.xyyzx.net/proxy/storagebox/docker.io/library/busybox" }}
        tag: 1.37.0
    replicated:
      enabled: true
    nfs-server:
      enabled: repl{{ ConfigOptionEquals "nfs_enabled" "1" }}
      imagePullSecrets:
        - name: repl{{ ImagePullSecretName }}
      persistence:
        shared:
          enabled: true
          type: emptyDir
          mountPath: repl{{ ConfigOption "nfs_share" }}
      env:
        NFS_EXPORT_0: repl{{ ConfigOption "nfs_share" }} repl{{ ConfigOption "nfs_share_options" }}
        NFS_LOG_LEVEL: debug
    cassandra:
      enabled: repl{{ ConfigOptionEquals "cassandra_enabled" "1" }}
      mode: repl{{ ConfigOption "cassandra_mode" }}
      auth:
        username: repl{{ ConfigOption "cassandra_user" }}
        password: repl{{ ConfigOption "cassandra_password" }}
      tls:
        enabled: repl{{ ConfigOptionEquals "cassandra_tls_enabled" "1" }}
      datacenters:
        - name: dc1
          size: repl{{ ConfigOption "cassandra_datacenter_size" }}
          storageConfig:
            storageClassName: repl{{ ConfigOption "cassandra_storage_class" }}
            size: repl{{ ConfigOption "cassandra_storage_size" }}
          resources: {}
          config:
            cassandraYaml:
              num_tokens: 256
              authenticator: PasswordAuthenticator
              authorizer: CassandraAuthorizer
            jvmOptions:
              heapSize: repl{{ ConfigOption "cassandra_heap_size" }}
      telemetry:
        prometheus:
          enabled: repl{{ ConfigOptionEquals "cassandra_prometheus_enabled" "1" }}
    postgres:
      enabled: repl{{ ConfigOptionEquals "postgres_enabled" "1" }}
      auth:
        username: repl{{ ConfigOption "postgres_user" }}
        password: repl{{ ConfigOption "postgres_password" }}
      embedded:
        image:
          repository: repl{{ HasLocalRegistry | ternary (print LocalRegistryHost "/cloudnative-pg/postgresql") "proxy.xyyzx.net/proxy/storagebox/ghcr.io/cloudnative-pg/postgresql" }}
        imagePullSecrets:
          - name: repl{{ ImagePullSecretName }}
        enabled: 'repl{{ ConfigOptionNotEquals "postgres_external" "1" }}'
        instances: repl{{ ConfigOption "postgres_instances" }}
        initdb:
          database: repl{{ ConfigOption "postgres_db" }}
          owner: repl{{ ConfigOption "postgres_db_owner" }}
        storage:
          size: repl{{ ConfigOption "postgres_storage_size" }}
          storageClass: repl{{ ConfigOption "postgres_storage_class" }}
        logLevel: repl{{ ConfigOption "postgres_log_level" }}
        service:
          type: NodePort
      external:
        enabled: repl{{ ConfigOptionEquals "postgres_external" "1" }}
        host: repl{{ ConfigOption "postgres_external_host" }}
        port: repl{{ ConfigOption "postgres_external_port" }}
        database: repl{{ ConfigOption "postgres_external_database" }}
    tenant:
      enabled: repl{{ ConfigOptionEquals "minio_tenant_enabled" "1" }}
      tenant:
        name: repl{{ ConfigOption "minio_tenant_name" }}
        image:
          repository: repl{{ HasLocalRegistry | ternary (print LocalRegistryHost "/minio/minio") "proxy.xyyzx.net/proxy/storagebox/quay.io/minio/minio" }}
          tag: RELEASE.2024-08-17T01-24-54Z
        imagePullSecret:
          name: repl{{ ImagePullSecretName }}
        configuration:
          name: minio-env-configuration
        certificate:
          requestAutoCert: repl{{ ConfigOptionEquals "minio_tenant_tls_auto_cert" "1" }}
        configSecret:
          name: minio-env-configuration
          accessKey: repl{{ ConfigOption "minio_tenant_configuration_access_key" }}
          secretKey: repl{{ ConfigOption "minio_tenant_configuration_secret_key" }}
        ingress:
          api:
            enabled: true
            ingressClassName: nginx
            host: repl{{ ConfigOption "minio_tenant_ingress_api_host" }}
            path: /
            pathType: Prefix
          console:
            enabled: true
            ingressClassName: nginx
            host: repl{{ ConfigOption "minio_tenant_ingress_console_host" }}
            path: /
            pathType: Prefix
        pools:
          - name: repl{{ ConfigOption "minio_tenant_pool_name" }}
            servers: repl{{ ConfigOption "minio_tenant_pool_servers" }}
            volumesPerServer: repl{{ ConfigOption "minio_tenant_pool_volumes_per_server" }}
            size: repl{{ ConfigOption "minio_tenant_pool_size" }}
            storageClassName: repl{{ ConfigOption "minio_tenant_pool_storage_class_name" }}
        metrics:
          enabled: repl{{ ConfigOptionEquals "minio_tenant_metrics_enabled" "1" }}
          port: repl{{ ConfigOption "minio_tenant_metrics_port" }}
          protocol: repl{{ ConfigOption "minio_tenant_metrics_protocol" }}
        buckets:
          - name: repl{{ ConfigOption "minio_tenant_bucket_name" }}
            objectLock: repl{{ ConfigOptionEquals "minio_tenant_bucket_object_lock" "1" }}
            region: repl{{ ConfigOption "minio_tenant_bucket_region" }}
    rqlite:
      enabled: repl{{ ConfigOptionEquals "rqlite_enabled" "1" }}
      replicas: repl{{ ConfigOption "rqlite_replicas" }}
      image:
        repository: repl{{ HasLocalRegistry | ternary (print LocalRegistryHost "/rqlite/rqlite") "proxy.xyyzx.net/proxy/storagebox/docker.io/rqlite/rqlite" }}
        tag: repl{{ ConfigOption "rqlite_image_tag" }}
        pullPolicy: repl{{ ConfigOption "rqlite_image_pull_policy" }}
        pullSecrets:
          - name: repl{{ ImagePullSecretName }}
      persistence:
        size: repl{{ ConfigOption "rqlite_storage_size" }}
        storageClassName: repl{{ ConfigOption "rqlite_storage_class" }}

  optionalValues:
    - when: 'repl{{ ConfigOptionEquals "cassandra_mode" "full" }}'
      recursiveMerge: true
      values:
        cassandra:
          reaper:
            enabled: true
