apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: license-validation
spec:
  title: License Validation Demo
  icon: ""
  releaseNotes: ""
  allowRollback: true
  requireMinimalRBACPrivileges: false
  supportMinimalRBACPrivileges: false
  ports:
    - serviceName: license-validation
      servicePort: 80
      localPort: 8888
      applicationUrl: "http://license-validation"
  statusInformers:
    - deployment/license-validation
  graphs: []
