apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: replicated
spec:
  chart:
    name: replicated
  weight: 1
  
  # helmUpgradeFlags specifies additional flags to pass to the `helm upgrade` command.
  helmUpgradeFlags:
    - --skip-crds
    - --timeout
    - 30s
    - --history-max=15
    - --wait

  values: 
    replicated:
      image:
        registry: '{{repl HasLocalRegistry | ternary LocalRegistryHost "registry.replicated.com" }}'
        repository: '{{repl HasLocalRegistry | ternary LocalRegistryNamespace "library" }}/replicated-sdk-image'
      imagePullSecrets:
        - name: '{{repl ImagePullSecretName }}'
  namespace: replicated
  builder: {}
