apiVersion: embeddedcluster.replicated.com/v1beta1
kind: Config
spec:
  version: 2.3.0+k8s-1.30
  roles:
    controller:
      name: controller
      labels:
        controller: "true"
    custom:
    - name: worker
      labels:
        worker: "true"
  unsupportedOverrides:
    k0s: |
      config:
        spec:
          workerProfiles:
            - name: increased-pod-limit
              values:
                maxPods: 250
