apiVersion: v2
dependencies:
- name: common
  repository: https://bjw-s-labs.github.io/helm-charts
  version: 4.6.2
- name: templates
  version: '*'
  repository: file://../templates
- name: replicated
  version: 1.18.0
  repository: oci://registry.replicated.com/library
description: Simple wireguard with web configuration management
home: https://github.com/replicatedhq/platform-examples/
maintainers:
- name: Replicated, Inc.
  url: https://github.com/replicatedhq/platform-examples/
name: wg-easy
version: 1.0.0
