name: wg-easy
version: 1.0.0
apiVersion: v2
dependencies:
  - name: wg-easy
    version: '1.0.0'
    repository: file://../wg-easy-upstream
  - name: templates
    version: '*'
    repository: file://../templates
