apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "mlflow"
spec:
  descriptor:
    version: "0.3.0"
    description: "MLflow"
    icon: https://mlflow.org/img/mlflow-black.svg
    links:
      - description: 🔗 Open MLflow
        url: 'http://{{repl ConfigOption "mlflow_ingress_host" }}'
