# Base image for all shared Containerfiles for taskfiles
# Use this image as base image for app specific container files
# this first container is only used to fetch deps and build tools
FROM --platform=$BUILDPLATFORM ubuntu:24.04 as build

ARG TARGETOS
ARG TARGETARCH

WORKDIR /tools

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive \
    HOME=/home/devuser \
    SHELL=/bin/bash \
    GOBIN=/tools

# Install debian packages
RUN apt-get update && apt-get install -y ca-certificates curl golang git make

# Install kubectl
run curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/${TARGETARCH}/kubectl" && chmod +x kubectl

# Install helm
RUN curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

# Install Task
run go install github.com/go-task/task/v3/cmd/task@latest

# Install Helmfile
run go install github.com/helmfile/helmfile@latest

# Install Replicated CLI
# TODO: we should look at why we can't use go install on our own cli
run git clone https://github.com/replicatedhq/replicated.git
run make -C replicated build

# this container is what will actually be committed
FROM --platform=$BUILDPLATFORM ubuntu:24.04
RUN apt-get update && apt-get install -y curl jq less yq

# copy other tools
copy --from=build /usr/local/bin/helm /usr/bin/helm
copy --from=build /tools/task /usr/bin/task
copy --from=build /tools/helmfile /usr/bin/helmfile
copy --from=build /tools/kubectl /usr/bin/kubectl
copy --from=build /tools/replicated/bin/replicated /usr/bin/replicated
