# Base image for all shared Dockerfiles for taskfiles
# Use this image as base image for app specific docker files
FROM --platform=$BUILDPLATFORM ubuntu:24.04

ARG TARGETOS
ARG TARGETARCH

WORKDIR /tools

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive \
    HOME=/home/devuser

# Install CLI tools
RUN apt-get update && apt-get install -y \
    curl \
    jq \
    yq \
    gnupg \
    sudo \

    # Install Helm
    && curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash \

    # Install kubectl
    && curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && chmod +x kubectl \
    && mv kubectl /usr/local/bin/ \

    # Install Task
    && sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin \

    # Install Helmfile
    && curl -Ls $(curl -s https://api.github.com/repos/helmfile/helmfile/releases/latest \
    | grep "browser_download_url.*linux_amd64.tar.gz" \
    | cut -d : -f 2,3 \
    | tr -d \") -o helmfile.tar.gz \
    && tar xf helmfile.tar.gz helmfile && rm helmfile.tar.gz \
    && mv helmfile /usr/local/bin/helmfile \

    # Install Replicated CLI
    && curl -Ls $(curl -s https://api.github.com/repos/replicatedhq/replicated/releases/latest \
    | grep "browser_download_url.*linux_amd64.tar.gz" \
    | cut -d : -f 2,3 \
    | tr -d \") -o replicated.tar.gz \
    && tar xf replicated.tar.gz replicated && rm replicated.tar.gz \
    && mv replicated /usr/local/bin/replicated \

    # Install Google Cloud CLI
    && echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list \
    && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg \
    && apt-get update \
    && apt-get install google-cloud-cli -y \
    && rm -rf /var/lib/apt/lists/*

# Create a non-root user for better security
RUN groupadd -r devuser \
    && useradd -r -g devuser -m -s /bin/bash devuser \
    && echo "devuser ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/devuser

# Set working directory
WORKDIR /app

# Switch to non-root user
USER devuser

CMD ["bash"]
