apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-preflights
  labels:
    troubleshoot.sh/kind: preflight
type: Opaque
stringData:
  preflight.yaml: |
    apiVersion: troubleshoot.sh/v1beta2
    kind: Preflight
    metadata:
      name: cert-manager-preflights
    spec:
      analyzers:
        - distribution:
            outcomes:
            - pass:
                when: "== gke"
                message: GKE is a supported platform
            - pass:
                when: "== k3s"
                message: K3S is a supported platform
            - fail:
                when: "== kind"
                message: This application does not support Kind
            - warn:
                message: The Kubernetes platform is not validated, but there are no known compatibility issues.