apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: traefik
spec:
  chart:
    name: traefik
  weight: 2
  helmUpgradeFlags:
    - --wait
  values:
    traefik:
      image:
        registry: '{{repl HasLocalRegistry | ternary LocalRegistryHost "docker.io" }}'
        repository: '{{repl HasLocalRegistry | ternary LocalRegistryNamespace "library" }}/traefik'
      deployment:
        imagePullSecrets:
          - name: '{{repl ImagePullSecretName }}'
  namespace: traefik
  builder: {}
