{{ if dig "replicated" "imagePullSecret" "enabled" false .Values.AsMap }}
apiVersion: v1
kind: Secret
metadata:
  # Note: Do not use "replicated" for the name of the pull secret
  name: replicated-pull-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  # dockerconfigjson from Replicated Helm CLI installs is already a base64 encoded string
  .dockerconfigjson: {{ .Values.global.replicated.dockerconfigjson }}
{{ end }}
