{{- range .Values.traefikRouteTCP }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  {{- if .routeName }}
  name: {{ .routeName }}
  {{- else }}
  name: {{ .serviceName }}
  {{- end }}
spec:
  entryPoints:
  {{- range .entryPoints }}
  - "{{ . }}"
  {{- end }}
  routes:
  - match: HostSNI(`*`)
    services:
    - name: {{ .serviceName }}
      port: {{ .servicePort }}
{{- end }}
