apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: nginx
  annotations:
    kots.io/when: '{{repl not IsKurl }}'
spec:
  type: ClusterIP
  ports:
    - port: 443
  selector:
    app: server
---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: nginx
  annotations:
    kots.io/when: '{{repl IsKurl }}'
spec:
  type: NodePort
  ports:
    - port: 443
      nodePort: 8843
  selector:
    app: server
