apiVersion: v2
name: wordpress-microservice
description: A Helm chart for deploying WordPress with MariaDB
type: application
version: 0.1.0
appVersion: 1.0.0
dependencies:
- name: replicated
  repository: oci://registry.replicated.com/library
  version: 1.0.0-beta.31
