---
apiVersion: v2
description: A Helm chart for cloudnative-pg operator
name: cloudnative-pg
type: application
version: 0.23.2
appVersion: 1.25.1
kubeVersion: '>=1.26.0-0'
dependencies:
- name: cloudnative-pg
  version:  0.23.2"
  repository: https://cloudnative-pg.github.io/charts
  condition: cloudnative-pg.enabled
