apiVersion: embeddedcluster.replicated.com/v1beta1
kind: Config
spec:
  version: 2.13.3+k8s-1.33
  extensions:
    helm:
      repositories:
        - name: ingress-nginx
          url: https://kubernetes.github.io/ingress-nginx
        - name: cnpg
          url: https://cloudnative-pg.github.io/charts
        - name: jetstack
          url: https://charts.jetstack.io
      charts:
        - name: ingress-nginx
          chartname: ingress-nginx/ingress-nginx
          namespace: ingress-nginx
          version: "4.14.1"
          values: |
            controller:
              service:
                type: NodePort
                nodePorts:
                  http: 80
                  https: 443
        - name: cloudnative-pg
          chartname: cnpg/cloudnative-pg
          namespace: cnpg
          version: "0.27.0"
        - name: cert-manager
          chartname: jetstack/cert-manager
          namespace: cert-manager
          version: "v1.19.1"
          values: |
            crds:
              enabled: true
            prometheus:
              enabled: false
