apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: gitea
spec:
  title: Gitea
  allowRollback: false
  statusInformers:
    - deployment/kotsadm
    - deployment/gitea
    - deployment/gitea-valkey
