# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.5.1/charts/other/app-template/values.schema.json

#### PowerDNS User-Facing Application Configuration
# powerdns:

#### PowerDNS Workload Definitions
controllers:
  main:
    enabled: true
    strategy: Recreate
    type: deployment
    containers:
      main:
        image:
          repository: powerdns/pdns-recursor-50
          tag: 5.0.5
        env:
          DEBUG_CONFIG: 'yes'
    # pod:
    #   securityContext:
    #     capabilities:
    #       add:
    #         - NET_BIND_SERVICE

configMaps:
  config:
    enabled: true
    data:
      99-recursor.conf: |
        allow-from=0.0.0.0
        local-address=0.0.0.0
        local-port=5353

persistence:
  config:
    enabled: true
    type: configMap
    name: powerdns-recursor-config
    advancedMounts:
      main:
        main:
          - path: /etc/powerdns/recursor.d/99-recursor.conf
            subPath: 99-recursor.conf

service:
  main:
    controller: main
    ports:
      udp:
        # type: ClusterIP
        port: 53
        targetPort: 5353
        protocol: UDP
      tcp:
        # type: ClusterIP
        port: 53
        targetPort: 5353
        protocol: TCP
