certs:
  selfSigned: true
  installProduction: false
  installStaging: false
  dnsNames: []
traefik:
  service:
    type: NodePort
  ports:
    websecure:
      nodePort: 30443
  tlsStore:
    default:
      certificates:
        - secretName: traefik-self-signed
      defaultCertificate:
        secretName: traefik-self-signed
