---
apiVersion: v2
description: A Helm chart for cloudnative-pg operator
name: cloudnative-pg
type: application
version: 0.22.1
appVersion: 1.24.1
kubeVersion: '>=1.26.0-0'
maintainers:
  - name: adamancini
    email: ada@annarchy.net
dependencies:
- name: cloudnative-pg
  version: "0.22.1"
  repository: https://cloudnative-pg.github.io/charts
  condition: cloudnative-pg.enabled
