name: replicated
version: 1.7.0
apiVersion: v2
dependencies:
  - name: templates
    version: '*'
    repository: file://../templates
  - name: replicated
    repository: oci://registry.replicated.com/library
    version: 1.7.0
