{{- if .Values.cassandra.enabled }}
apiVersion: v1
data:
  keystore-password: {{ .Values.cassandra.keystore_password | b64enc }}
  truststore-password: {{ .Values.cassandra.truststore_password | b64enc }}
metadata:
  name: cassandra-credentials
kind: Secret
{{- end }}
