{{- if .Values.postgres.embedded.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-initdb-secret
  {{- with .Values.postgres.embedded.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
  {{- end }}
  labels:
  {{- with .Values.postgres.embedded.additionalLabels }}
    {{ toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.postgres.auth.username }}
  password: {{ .Values.postgres.auth.password }}
{{- end -}}
