apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "storagebox.labels" . | nindent 4 }}
    troubleshoot.sh/kind: preflight
  name: "{{ .Release.Name }}-preflight-config"
stringData:
  preflight.yaml: |
    {{- include "storagebox.preflight" . | nindent 4 }}
