{{- if .Values.certmanager.selfSignedClusterIssuer.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}-selfsigned-issuer
spec:
  selfSigned: {}
{{- end }}
