apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: fake-service
  message: thisistheway
spec:
  descriptor:
    links:
      - description: Open App
        url: https://repl{{ ConfigOption "hostname" }}
