apiVersion: embeddedcluster.replicated.com/v1beta1
kind: Config
spec:
  version: 2.1.2+k8s-1.30
  roles:
    controller:
      name: management
      labels:
        management: "true"
    custom:
      - name: app
        labels:
          app: "true"
  unsupportedOverrides:
    k0s: |
      config:
        spec:
          api:
            extraArgs:
              service-node-port-range: 80-32767
