apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: gitlab
spec:
  collectors:
    - clusterInfo: {}
    - clusterResources: {}
    - logs:
        selector:
          - app=webservice
          - release=gitlab
        namespace: '{{repl Namespace }}'
        limits:
          maxAge: 720h
          maxLines: 10000
    - logs:
        selector:
          - app=sidekiq
          - release=gitlab
        namespace: '{{repl Namespace }}'
        limits:
          maxAge: 720h
          maxLines: 10000
    - logs:
        selector:
          - app=kas
          - release=gitlab
        namespace: '{{repl Namespace }}'
        limits:
          maxAge: 720h
          maxLines: 10000
    - logs:
        selector:
          - app=redis-master
          - release=gitlab
        namespace: '{{repl Namespace }}'
        limits:
          maxAge: 720h
          maxLines: 5000
    - logs:
        selector:
          - app=postgresql
          - release=gitlab
        namespace: '{{repl Namespace }}'
        limits:
          maxAge: 720h
          maxLines: 5000
