---
# Secret for PostgreSQL password — referenced by the GitLab chart
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-postgresql-password
type: Opaque
stringData:
  postgresql-password: 'repl{{ ConfigOption "postgres_password" }}'
---
# Secret for Redis password — referenced by the GitLab chart
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-redis-password
type: Opaque
stringData:
  redis-password: 'repl{{ ConfigOption "redis_password" }}'
