{{- if .Values.gateway.enabled -}}
{{- $fullName := include "flipt.fullname" . -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flipt.labels" . | nindent 4 }}
  {{- if .Values.gateway.tls }}
  annotations:
    cert-manager.io/cluster-issuer: {{ (index .Values.gateway.annotations "cert-manager.io/cluster-issuer") | default "letsencrypt-prod" | quote }}
  {{- end }}
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      {{- if .Values.gateway.hosts }}
      allowedRoutes:
        namespaces:
          from: Same
      {{- end }}
  {{- if .Values.gateway.tls }}
    - name: https
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          {{- range .Values.gateway.tls }}
          - name: {{ .secretName }}
          {{- end }}
      {{- if .Values.gateway.hosts }}
      allowedRoutes:
        namespaces:
          from: Same
      {{- end }}
  {{- end }}
{{- end }}
