{{- if .Values.gateway.enabled -}}
{{- $fullName := include "flipt.fullname" . -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flipt.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ $fullName }}
      namespace: {{ .Release.Namespace }}
      sectionName: {{ if .Values.gateway.tls }}https{{ else }}http{{ end }}
  {{- if .Values.gateway.hosts }}
  hostnames:
    {{- range .Values.gateway.hosts }}
    - {{ .host | quote }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.gateway.hosts }}
    {{- range .paths }}
    {{- $pt := .pathType | default "PathPrefix" }}
    {{- if or (eq $pt "Prefix") (eq $pt "ImplementationSpecific") }}{{- $pt = "PathPrefix" }}{{- end }}
    - matches:
        - path:
            type: {{ $pt }}
            value: {{ .path }}
      backendRefs:
        - name: {{ default $fullName ((default dict .backend).serviceName) }}
          port: {{ $.Values.service.httpPort | default 8080 }}
    {{- end }}
    {{- end }}
{{- end }}
