{{- if and .Values.licenseSync.enabled .Values.licenseSync.publicKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flipt.fullname" . }}-license-sync-key
  labels:
    {{- include "flipt.labels" . | nindent 4 }}
    app.kubernetes.io/component: license-sync
type: Opaque
stringData:
  public-key.pem: |
{{ .Values.licenseSync.publicKey | indent 4 }}
{{- end }}
