name: 'Test Deployment - DEPRECATED'
description: 'This action has been deprecated and replaced with individual workflow steps in Phase 4 of the replicated-actions refactoring. See wg-easy-pr-validation.yaml for the new implementation.'

inputs:
  app-dir:
    description: 'DEPRECATED - This action is no longer used'
    deprecated: true
  customer-name:
    description: 'DEPRECATED - This action is no longer used'
    deprecated: true
  cluster-name:
    description: 'DEPRECATED - This action is no longer used'
    deprecated: true
  channel-name:
    description: 'DEPRECATED - This action is no longer used'
    deprecated: true
  channel-id:
    description: 'DEPRECATED - This action is no longer used'
    deprecated: true
  channel-slug:
    description: 'DEPRECATED - This action is no longer used'
    deprecated: true
  helm-version:
    description: 'DEPRECATED - This action is no longer used'
    deprecated: true
  cleanup:
    description: 'DEPRECATED - This action is no longer used'
    deprecated: true

runs:
  using: 'composite'
  steps:
    - name: Action Deprecated
      shell: bash
      run: |
        echo "::error::This action has been deprecated in Phase 4 of the replicated-actions refactoring."
        echo "::error::The functionality has been moved to individual workflow steps in wg-easy-pr-validation.yaml"
        echo "::error::Please update your workflow to use the new individual steps instead of this composite action."
        exit 1
