apiVersion: embeddedcluster.replicated.com/v1beta1
kind: Config
spec:
  version: v1.2.0+k8s-1.29
  extensions:
    helm:
      repositories:
        - name: ingress-nginx
          url: https://kubernetes.github.io/ingress-nginx
        - name: cnpg
          url: https://cloudnative-pg.github.io/charts
        - name: minio
          url: https://operator.min.io/
      charts:
        - name: ingress-nginx
          chartname: ingress-nginx/ingress-nginx
          namespace: ingress-nginx
          version: "4.10.1"
          values: |
            controller:
              service:
                type: NodePort
                nodePorts:
                  http: "80"
                  https: "443"
        - name: cloudnative-pg
          chartname: cnpg/cloudnative-pg
          namespace: cloudnative-pg
          version: "0.21.2"
        - name: minio-operator
          chartname: minio/operator
          namespace: minio
          version: "5.0.15"
          values: |
            console:
              enabled: false
  unsupportedOverrides:
    k0s: |
      config:
        spec:
          api:
            extraArgs:
              service-node-port-range: 80-32767
