apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: infra
spec:
  chart:
    name: infra
    chartVersion: 0.3.0
  exclude: 'repl{{ ConfigOptionEquals `postgres_type` `external_postgres` }}'
  weight: -10
  helmUpgradeFlags:
    - --wait
    - --timeout
    - 600s
  values:
    crdCheck:
      image:
        registry: repl{{ HasLocalRegistry | ternary LocalRegistryHost "docker.io" }}
        repository: 'repl{{HasLocalRegistry | ternary LocalRegistryNamespace "bitnami" }}/kubectl'
    cloudnative-pg:
      image:
        repository: '{{repl HasLocalRegistry | ternary LocalRegistryHost "ghcr.io" }}/{{repl HasLocalRegistry | ternary LocalRegistryNamespace "cloudnative-pg" }}/cloudnative-pg'
    minio-operator:
      console:
        enabled: false
      image:
        repository: '{{repl HasLocalRegistry | ternary LocalRegistryHost "quay.io" }}/{{repl HasLocalRegistry | ternary LocalRegistryNamespace "minio" }}/operator'
