apiVersion: troubleshoot.replicated.com/v1beta1
kind: SupportBundle
metadata:
  name: mlflow
spec:
  collectors:
    - clusterInfo: {}
    - clusterResources: {}
    - logs:
        selector:
          - app.kubernetes.io/name=mlflow
        namespace: '{{repl Namespace }}'
        limits:
          maxAge: 720h
          maxLines: 10000
