apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: mlflow
spec:
  uri: https://raw.githubusercontent.com/replicatedhq/platform-examples/main/applications/mlflow/kots/kots-support-bundle.yaml
  collectors:
    - clusterInfo: {}
    - clusterResources: {}
    - logs:
        selector:
          - app.kubernetes.io/name=mlflow
        namespace: '{{repl Namespace }}'
        limits:
          maxAge: 720h
          maxLines: 10000
