apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: mlflow
spec:
  # chart identifies a matching chart from a .tgz
  chart:
    name: mlflow
    chartVersion: 0.1.2

  # values are used in the customer environment, as a pre-render step
  # these values will be supplied to helm template
  values:
    ingress:
      enabled: true
      annotations: 
        kubernetes.io/ingress.class: nginx
      hosts:
        - host: 'repl{{ ConfigOption "mlflow_ingress_host"}}'
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: mlfow-tls
          hosts:
            - 'repl{{ ConfigOption "mlflow_ingress_host"}}'
    tls:
      enabled: repl{{ ConfigOptionEquals "mlflow_ingress_type" "ingress_controller" }}
      genSelfSignedCert: repl{{ ConfigOptionEquals "mlflow_ingress_tls_type" "self_signed" }}
      cert: repl{{ print `|`}}repl{{ ConfigOptionData `mlflow_ingress_tls_cert` | nindent 8 }}
      key: repl{{ print `|`}}repl{{ ConfigOptionData `mlflow_ingress_tls_key` | nindent 8 }}

  # builder values provide a way to render the chart with all images
  # and manifests. this is used in replicated to create airgap packages
  builder: {}
