apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: mlflow
spec:
  title: MLflow
  icon: https://mlflow.org/img/mlflow-black.svg
  releaseNotes: |
    # MLflow
    MLflow is an open-source platform for managing the end-to-end machine learning lifecycle.
  allowRollback: false
  #statusInformers:
  #  - deployment/mlflow
  #  - services/mlflow
  ports:
    - serviceName: "mlflow"
      servicePort: 5000
      localPort: 5000
      applicationUrl: "http://mlflow"
