apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: minio-operator
spec:
  chart:
    name: operator
    chartVersion: 5.0.15
  exclude: 'repl{{ or (ConfigOptionEquals `s3_type` `external_s3`) (eq Distribution "embedded-cluster") }}'
  weight: -10
  value:
    console:
      enabled: false
    image:
      repository: '{{repl HasLocalRegistry | ternary LocalRegistryHost "quay.io" }}/{{repl HasLocalRegistry | ternary LocalRegistryNamespace "minio" }}/operator'
  helmUpgradeFlags:
    - --wait
    - --timeout
    - 600s
