apiVersion: v2
description: Replicated library chart
home: https://github.com/replicatedhq/helm-charts/tree/main/charts/replicated-library
keywords:
- replicated-library
kubeVersion: '>=1.16.0-0'
maintainers:
- email: diamon@replicated.com
  name: diamonwiggins
- email: chriss@replicated.com
  name: chris-sanders
name: replicated-library
type: library
version: 0.13.10
