apiVersion: v1
kind: Secret
metadata:
  name: {{ include "license-validation.fullname" . }}-preflight
  labels:
    {{- include "license-validation.labels" . | nindent 4 }}
    troubleshoot.sh/kind: preflight
type: Opaque
stringData:
  preflight.yaml: |
    {{ include "license-validation.preflight" . | nindent 4 }}
