{{- if .Values.appPublicKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "license-validation.fullname" . }}-public-key
  labels:
    {{- include "license-validation.labels" . | nindent 4 }}
type: Opaque
stringData:
  public-key: {{ .Values.appPublicKey | quote }}
{{- end }}
