  apiVersion: kots.io/v1beta1
  kind: Config
  metadata:
    name: replibot-config
  spec:
    groups:
      - name: replibot
        title: replibot
        description: replibot Configuration
        items:
          - name: admin_user
            title: Admin User
            type: text
            default: 'admin'
          - name: admin_password
            title: Admin Password
            type: password
            default: 'admin'
