apps:
  metalytics-worker:
    enabled: true
    type: deployment
    replicas: 1
    containers:
      worker:
        image:
          repository: metalytics-worker
          tag: latest
        envFrom:
          - secretRef:
              name: metalytics

  metalytics-api:
    enabled: true
    type: deployment
    replicas: 1
    containers:
      api:
        image:
          repository: metalytics-api
          tag: latest
        ports:
        - name: http
          containerPort: 8080
        envFrom:
        - secretRef:
            name: metalytics

services:
  metalytics-api:
    enabled: true
    appName: ["metalytics-api"]
    type: NodePort
    ports:
      http:
        enabled: true
        port: 8080
        protocol: HTTP
        targetPort: 8080
        nodePort: 8080

secrets:
  metalytics:
    enabled: true
    data:
      LOG_LEVEL: "debug"
      API_URL: "http://metalytics-api:8080"
      # ... etc
