apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultwarden.fullname" . }}
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "vaultwarden.databaseUrl" . | quote }}
  {{- if .Values.vaultwarden.adminToken }}
  ADMIN_TOKEN: {{ .Values.vaultwarden.adminToken | quote }}
  {{- end }}
  {{- if .Values.vaultwarden.smtp.enabled }}
  SMTP_PASSWORD: {{ .Values.vaultwarden.smtp.password | quote }}
  {{- end }}
