---
# Custom TLS Secret for Ingress
# Only deployed when user selects "Upload Custom Certificate" for TLS
apiVersion: v1
kind: Secret
metadata:
  name: flipt-custom-tls
  namespace: 'repl{{ ConfigOption "namespace" }}'
  labels:
    app.kubernetes.io/name: flipt
    app.kubernetes.io/instance: 'repl{{ ConfigOption "release_name" }}'
  annotations:
    # Exclude this secret unless custom TLS is configured
    kots.io/exclude: '{{repl not (and (ConfigOptionEquals "ingress_enabled" "1") (ConfigOptionEquals "tls_enabled" "1") (ConfigOptionEquals "tls_cert_source" "custom")) }}'
type: kubernetes.io/tls
data:
  tls.crt: 'repl{{ ConfigOptionData "tls_cert" | Base64Encode }}'
  tls.key: 'repl{{ ConfigOptionData "tls_key" | Base64Encode }}'
