{{- if .Values.crdCheck.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "crdCheck.fullname" . }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "crdCheck.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "crdCheck.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
