apiVersion: v1
kind: Service
metadata:
  name: {{ include "flagd.fullname" . }}
  labels:
    {{- include "flagd.labels" . | nindent 4 }}
  {{- with .Values.flagd.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.flagd.service.type }}
  ports:
  - port: {{ .Values.flagd.service.grpcPort }}
    targetPort: grpc
    protocol: TCP
    name: grpc
  - port: {{ .Values.flagd.service.httpPort }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "flagd.selectorLabels" . | nindent 4 }}
