{{- if .Values.customMetrics.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-metrics-config
  labels:
    app: {{ .Chart.Name }}
data:
  customMetrics.yaml: |
    exporters:
    {{- range .Values.customMetrics.exporters }}
      - name: {{ .name }}
        endpoint: {{ .endpoint }}
        description: {{ .description }}
        interval: {{ .interval }}
    {{- end }}
{{- end }}
