{{- if not .Values.database.embedded }}  # Only create this Secret when using an external DB
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-external-db-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  host: {{ .Values.database.external.host | b64enc }}
  port: {{ .Values.database.external.port | toString | b64enc }}
  username: {{ .Values.database.external.user | b64enc }}
  password: {{ .Values.database.external.password | b64enc }}
  database: {{ .Values.database.external.name | b64enc }}
{{- end }}

