apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    {{- include "wordpress-microservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mariadb.service.type }}
  ports:
    - port: {{ .Values.mariadb.service.port }}
      targetPort: 3306
  selector:
    {{- include "wordpress-microservice.selectorLabels" . | nindent 4 }}
    #app: mariadb
