{{- if .Values.database.embedded }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.database.user | b64enc }}
  password: {{ .Values.database.password | default (randAlphaNum 16) | b64enc }}
  root-password: {{ .Values.database.rootPassword | default (randAlphaNum 16) | b64enc }}
  database: {{ .Values.database.name | b64enc }}
{{- end }}
