apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    {{- include "wordpress-microservice.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.wordpress.replicaCount }}
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: "{{ .Values.wordpress.image.repository }}:{{ .Values.wordpress.image.tag }}"
          imagePullPolicy: {{ .Values.wordpress.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: "{{ if .Values.database.embedded }}{{ .Release.Name }}-mariadb{{ else }}{{ .Values.database.external.host }}{{ end }}"
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.database.embedded }}{{ .Release.Name }}-db-secret{{ else }}{{ .Values.database.external.secretName }}{{ end }}
                  key: username
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.database.embedded }}{{ .Release.Name }}-db-secret{{ else }}{{ .Values.database.external.secretName }}{{ end }}
                  key: password
            - name: WORDPRESS_DB_NAME
              value: "{{ .Values.database.name }}"
