---
apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: wg-easy
spec:
  title: wg-easy
  icon: https://www.logo.wine/a/logo/WireGuard/WireGuard-Icon-Logo.wine.svg
  allowRollback: true
  additionalImages:
   - debian:buster-slim
  additionalNamespaces: []
  #additionalNamespaces should be populated by the Task file
  statusInformers:
    - wg-easy/deployment/wg-easy
    - traefik/deployment/traefik
    - cert-manager/deployment/cert-manager
    - cert-manager/deployment/cert-manager-cainjector
    - cert-manager/deployment/cert-manager-webhook
