# yaml-language-server: $schema=https://raw.githubusercontent.com/replicatedhq/embedded-cluster/refs/heads/main/operator/schemas/config-embeddedcluster-v1beta1.json

apiVersion: embeddedcluster.replicated.com/v1beta1
kind: Config
spec:
  version: 2.8.1+k8s-1.31
  domains:
    proxyRegistryDomain: proxy.xdrcft.net
    replicatedAppDomain: app.xdrcft.net
  unsupportedOverrides:
    k0s: |-
      config:
        spec:
          workerProfiles:
            - name: default
              values:
                allowedUnsafeSysctls:
                  - net.ipv4.ip_forward
