apiVersion: v1
kind: Secret
metadata:
  name: traefik-supportbundle
  labels:
    troubleshoot.sh/kind: support-bundle
type: Opaque
stringData:
  support-bundle-spec: |
{{ include "traefik.supportbundle" . | indent 4 }} 
