apiVersion: v1
kind: Secret
metadata:
  name: wg-easy-preflights
  labels:
    troubleshoot.sh/kind: preflight
type: Opaque
stringData:
  preflight.yaml: |
{{ include "wg-easy.preflight" . | indent 4 }} 