apiVersion: v1
kind: Secret
metadata:
  name: wg-easy-supportbundle
  labels:
    troubleshoot.sh/kind: support-bundle
type: Opaque
stringData:
  support-bundle-spec: |
{{ include "wg-easy.supportbundle" . | indent 4 }} 
