apiVersion: v1
kind: Secret
metadata:
  name: wg-easy-preflights
  labels:
    troubleshoot.sh/kind: preflight
type: Opaque
stringData:
  preflight.yaml: |
    apiVersion: troubleshoot.sh/v1beta2
    kind: Preflight
    metadata:
      name: wg-easy-preflights
    spec:
      collectors:
        - sysctl:
            image: debian:buster-slim
      analyzers:
        - sysctl:
            checkName: IP forwarding enabled
            outcomes:
              - fail:
                  when: 'net.ipv4.ip_forward == 0'
                  message: "IP forwarding must be enabled. To enable it, edit /etc/sysctl.conf, add or uncomment the line 'net.ipv4.ip_forward=1', and run 'sudo sysctl -p'."
              - pass:
                  when: 'net.ipv4.ip_forward == 1'
                  message: "IP forwarding is enabled."