apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: wg-easy
spec:
  chart:
    name: wg-easy
  weight: 3
  
  # helmUpgradeFlags specifies additional flags to pass to the `helm upgrade` command.
  helmUpgradeFlags:
    - --skip-crds
    - --timeout
    - 30s
    - --history-max=15
    - --wait

  values:
    service:
      vpn:
        ports:
          udp:
            port: repl{{ ConfigOption `vpn-port` | ParseInt  }}
    wireguard:
      password: repl{{ ConfigOption `password` }}
      host: repl{{ ConfigOption `domain` }}
      port: repl{{ ConfigOption `vpn-port` | ParseInt }}
    templates:
      traefikRoutes:
        web-tls:
          hostName: repl{{ ConfigOption `domain` }}
    controllers:
      wg-easy:
        containers:
          wg-container:
            image:
              repository: '{{repl HasLocalRegistry | ternary LocalRegistryHost "ghcr.io" }}/{{repl HasLocalRegistry | ternary LocalRegistryNamespace "wg-easy" }}/wg-easy'
  namespace: wg-easy
  builder: {}
