---
name: WG-Easy PR Cleanup - clean up resources after merge

on:
  pull_request:
    types: [closed]
    branches: [main]
    paths:
      - 'applications/wg-easy/**'
      - '.github/workflows/wg-easy-pr-validation.yaml'
      - '.github/workflows/wg-easy-pr-cleanup.yaml'

env:
  APP_DIR: applications/wg-easy
  REPLICATED_API_TOKEN: ${{ secrets.WG_EASY_REPLICATED_API_TOKEN }}
  REPLICATED_APP: ${{ secrets.WG_EASY_REPLICATED_APP }}

jobs:
  cleanup:
    runs-on: ubuntu-22.04
    # Only run cleanup when PR is actually merged to main
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set branch and channel variables
        id: vars
        run: |
          # Use the head branch name for cleanup (the branch that was merged)
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          # Channel name is normalized to lowercase with hyphens for Replicated channels
          CHANNEL_NAME=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' | tr '/' '-')
          echo "branch-name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "channel-name=$CHANNEL_NAME" >> $GITHUB_OUTPUT
          echo "Cleaning up resources for merged branch: $BRANCH_NAME (channel: $CHANNEL_NAME)"

      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          app-dir: ${{ env.APP_DIR }}

      - name: Cleanup PR resources
        run: |
          echo "Starting cleanup for merged PR branch: ${{ steps.vars.outputs.branch-name }}"
          task cleanup-pr-resources BRANCH_NAME="${{ steps.vars.outputs.channel-name }}" || echo "Cleanup completed with some warnings"
          echo "Cleanup completed for merged PR"
        working-directory: ${{ env.APP_DIR }}

      - name: Report cleanup status
        if: always()
        run: |
          if [ $? -eq 0 ]; then
            echo "✅ Successfully cleaned up resources for merged PR: ${{ steps.vars.outputs.branch-name }}"
          else
            echo "⚠️ Cleanup completed with warnings for merged PR: ${{ steps.vars.outputs.branch-name }}"
          fi