name: 'Create Replicated Release'
description: 'Create channel and release using Task-based operations'
inputs:
  app-dir:
    description: 'Application directory containing charts'
    default: 'applications/wg-easy'
  channel-name:
    description: 'Release channel name'
    required: true
  channel-id:
    description: 'Release channel ID (optional, takes precedence over channel-name)'
    required: false
  release-version:
    description: 'Release version'
    default: '0.0.1'
  release-notes:
    description: 'Release notes'
    default: 'Release created via GitHub Actions'

outputs:
  channel-id:
    description: 'Channel ID created or found'
    value: ${{ steps.channel.outputs.channel-id }}

runs:
  using: 'composite'
  steps:
    - name: Setup tools
      uses: ./.github/actions/setup-tools
    
    - name: Create channel
      id: channel
      shell: bash
      working-directory: ${{ inputs.app-dir }}
      run: |
        CHANNEL_ID=$(task channel-create RELEASE_CHANNEL="${{ inputs.channel-name }}" --silent | tail -1)
        echo "channel-id=$CHANNEL_ID" >> $GITHUB_OUTPUT
        echo "Created/found channel with ID: $CHANNEL_ID"
    
    - name: Create release
      shell: bash
      working-directory: ${{ inputs.app-dir }}
      run: |
        task release-create \
          RELEASE_CHANNEL="${{ inputs.channel-name }}" \
          RELEASE_VERSION="${{ inputs.release-version }}" \
          RELEASE_NOTES="${{ inputs.release-notes }}"